import React, { useState, useEffect, useRef } from "react";
import "./aiAssistant.css";
import { getAiResponse } from "../../../utils/aiAssistant";

export default function AiAssistantWindow() {
  const [messages, setMessages] = useState([
    { from: "ai", text: "Hey! I'm A63. Ask me anything about Marta." },
  ]);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  const chatRef = useRef(null);

  useEffect(() => {
    if (chatRef.current) {
      chatRef.current.scrollTop = chatRef.current.scrollHeight;
    }
  }, [messages, isTyping]);

  function handleSend(text) {
    if (!text.trim()) return;

    const userMsg = { from: "user", text };
    setMessages(prev => [...prev, userMsg]);
    setInput("");
    setIsTyping(true);

    setTimeout(() => {
      const aiText = getAiResponse(text);
      const aiMsg = { from: "ai", text: aiText };
      setMessages(prev => [...prev, aiMsg]);
      setIsTyping(false);
    }, 600);
  }

  return (
    <div className="ai-window">
      <div className="ai-chat-column" ref={chatRef}>
        {messages.map((m, i) => (
          <div key={i} className={`bubble ${m.from}`}>
            {m.text}
          </div>
        ))}
        {isTyping && <div className="bubble ai typing">A63 is thinking…</div>}
      </div>

      <div className="ai-spacer" />

      <div className="bottom-section">
        <div className="suggested-tags">
          <button className="tag" onClick={() => handleSend("Who is Marta?")}>
            Who is Marta?
          </button>
          <button className="tag" onClick={() => handleSend("Tell me about her work")}>
            Tell me about her work
          </button>
          <button className="tag" onClick={() => handleSend("What’s her design philosophy?")}>
            Design Philosophy
          </button>
          <button className="tag" onClick={() => handleSend("What are your career goals?")}>
            Career Goals
          </button>
        </div>

        <div className="ai-input">
          <input
            placeholder="Ask me anything…"
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => e.key === "Enter" && handleSend(input)}
          />
          <button onClick={() => handleSend(input)}>Send</button>
        </div>

        <div className="ai-footer">
          Response generated by AI · Prompt engineering work in progress
        </div>
      </div>
    </div>
  );
}