// src/components/windows/AiAssistant/AiAssistantWindow.jsx
import React from "react";
import "./aiAssistant.css";

export default function AiAssistantWindow() {
  return (
    <div className="ai-window">

      {/* White bubble at the top */}
      <div className="ai-chat-column">
        <div className="bubble ai">
          Hey! I'm A63. Ask me anything about Marta.
        </div>
      </div>

      {/* Spacer to push tags + input to the bottom */}
      <div className="ai-spacer" />

      {/* Tags + input bar together at the bottom */}
      <div className="bottom-section">

        <div className="suggested-tags">
          <button className="tag">Who is Marta?</button>
          <button className="tag">Tell me about her work</button>
          <button className="tag">What’s she into?</button>
        </div>

        <div className="ai-input">
          <input placeholder="Ask me anything…" />
          <button>Send</button>
        </div>

        <div className="ai-footer">
          Response generated by AI · Prompt engineering work in progress
        </div>

      </div>
    </div>
  );
}
